####################################################################################################
#
# EDA-RW — Python library to read/write EDA Sexpr file format
# Copyright (C) 2026 Fabrice SALVAIRE
# SPDX-License-Identifier: AGPL-3.0-or-later
#
####################################################################################################

# - [PEP 484 – Type Hints — Stub Files | peps.python.org](https://peps.python.org/pep-0484/#stub-files)
# - [Automatic stub generation (stubgen) - mypy 2.3.1 documentation](https://mypy.readthedocs.io/en/stable/stubgen.html)
# ty doesn't merge pi and .pyi

# find src -name "*pyi_" -exec mv {} __TRASH__ \;

# for TYPE_CHECKING
# def signal_def(~ERROR~ 'property' object has no attribute 'Signal'): ...
# def component_def(~ERROR~ name 'component' is not defined): ...
# def load(~ERROR~ name 'Project' is not defined): ...
# def project(~ERROR~ name 'Project' is not defined): ...
# def load(~ERROR~ name 'Project' is not defined): ...
# def load(~ERROR~ name 'Self' is not defined): ...

####################################################################################################

import annotationlib
import builtins
import inspect
import sys
from pathlib import Path
from typing import TYPE_CHECKING, Any, Literal, Self

from invoke import task, Context
from rich import print

from edarw.eda.librepcb import component, project, schematic, symbol
from edarw.sexpr import PositionalField, SexprWrapper
from edarw.text_buffer import TextBuffer

####################################################################################################

SOURCE_PATH = Path(__file__).parents[1]

STUB_HEADER = """
####################################################################################################
#
# EDA-RW — Python library to read/write EDA Sexpr file format
# Copyright (C) 2026 Fabrice SALVAIRE
# SPDX-License-Identifier: AGPL-3.0-or-later
#
# This file is generated by invoke task stub.generate
#
####################################################################################################

from collections.abc import Iterable, KeysView, ValuesView
from datetime import datetime
from pathlib import Path

import edarw.eda.librepcb.circuit
import edarw.eda.librepcb.common
import edarw.eda.librepcb.component
import edarw.eda.librepcb.schematic
import edarw.eda.librepcb.symbol
from edarw import geometry
from edarw import sexpr
from edarw.eda import librepcb
from edarw.eda.librepcb.common import LibreSexpr, UuidSexpr
from edarw.sexpr import SexprWrapper

####################################################################################################

type UUID = str
"""

####################################################################################################

def backup_file(path: Path) -> None:
    """Create a backup copy of a file by renaming it with a numbered suffix.

    This function renames the given file by appending a numbered backup suffix
    (~1~, ~2~, etc.) to find an available filename that doesn't already exist.

    Args:
        path: A Path object pointing to the file to be backed up.

    Returns:
        None
    """
    counter = 0
    while True:
        counter += 1
        old_path = path.parent / (path.name + f'~{counter}~')
        if not old_path.exists():
            break
    print(f"Rename {path} -> {old_path}")
    path.rename(old_path)

####################################################################################################

@task
def generate(ctx: Context, backup=False) -> None:
    src_path = SOURCE_PATH / 'src'
    librepcb_path = src_path / 'edarw/eda/librepcb'

    for root, _, files in librepcb_path.walk():
        for file in files:
            file_path = root / file
            if file_path.suffix == '.pyi':
                if backup:
                    backup_file(file_path)
                else:
                    file_path.unlink()

    def get_path(cls: object) -> tuple[Path, Path]:
        module_path = src_path / cls.__module__.replace('.', '/')
        pyi_path = module_path.parent / (module_path.name + '.pyi')
        return module_path, pyi_path

    for cls in SexprWrapper._CLASSES:
        module_path, pyi_path = get_path(cls)
        if not pyi_path.exists():
            buffer = TextBuffer()
            for line in STUB_HEADER.strip().split('\n'):
                if cls.__module__ not in line:
                    if line:
                        buffer += line
                    else:
                        buffer.new_line()
            print(f"Create [red]{pyi_path}")
            with open(pyi_path, 'w') as fh:
                fh.write(str(buffer))

    for cls in SexprWrapper._CLASSES:
        module_path, pyi_path = get_path(cls)

        buffer = TextBuffer()
        buffer.new_line()
        buffer += '#'*100
        buffer.new_line()

        base_class = cls.__mro__[1]
        buffer += f"class {cls.__name__}({base_class.__name__}):"
        buffer.indent()
        if cls.__doc__:
            buffer += f'"""{cls.__doc__}"""'

        def sig_doc(obj: Any) -> tuple[str, str | None, str | None]:
            globals = dict(sys.modules[obj.__module__].__dict__)
            type_checking_globals = {
                'Project': project.Project,
            }
            globals.update(type_checking_globals)
            comment = None
            try:
                signature = inspect.signature(
                    obj,
                    # globals=globals,
                    globals=type_checking_globals,
                    locals=type_checking_globals,
                )
            except (NameError, ValueError, TypeError, AttributeError) as e:
                print(f"inspect error for {cls.__name__}.{field}")
                signature = f'(self)'
                comment = f"# ~ERROR~: {e}"
            # print(annotationlib.get_annotations(obj, globals=type_checking_globals))
            doc = inspect.getdoc(obj)
            signature_str = str(signature)
            for _ in (
                    cls.__module__,
                    'collections.abc',
                    'datetime',
                    'pathlib',
                    'edarw.sexpr',
                    'edarw.eda.librepcb.common',
                    'edarw.eda',
                    'edarw',
            ):
                signature_str = signature_str.replace(_ + '.', '')
            return signature_str, doc, comment

        line_count = len(buffer)

        members = inspect.getmembers(cls)
        for name, obj in members:
            # skip inherited, dunder and private members
            if hasattr(base_class, name):
                continue
            if name.startswith('__') and name.endswith('__'):
                continue
            if name.startswith('_'):
                continue

            # inject methods and properties
            if inspect.isfunction(obj) or inspect.ismethod(obj):
                signature, doc, comment = sig_doc(obj)
                # if doc:
                #     buffer += f'"""{doc}"""'
                buffer += f"def {name}{signature}: ..."
            elif isinstance(obj, property):
                signature, doc, comment = sig_doc(obj.fget)
                buffer += "@property"
                buffer += f"def {name}{signature}: ..."
            else:
                comment = None
            if comment is not None:
                buffer += comment

        # Add annotation getters
        if len(buffer) != line_count:
            buffer.new_line()
        annotations = annotationlib.get_annotations(cls)
        for field, type_ in annotations.items():
            is_list = hasattr(type_, '__origin__') and type_.__origin__ == builtins.list
            is_tuple = hasattr(type_, '__origin__') and type_.__origin__ == builtins.tuple
            print(field, type_, is_tuple, is_list)
            match type_:
                case PositionalField():
                    type_str = type_.type.__name__
                case _:
                    if is_list:
                        obj_type = type_.__args__[0]
                        type_str = f'list[{obj_type.__name__}]'
                        print(type_str)
                    elif is_tuple:
                        obj_type = ', '.join(_.__name__ for _ in type_.__args__)
                        type_str = f'tuple[{obj_type}]'
                    else:
                        type_str = type_.__name__
            buffer += "@property"
            buffer += f"def {field}(self) -> {type_str}: ..."

        if len(buffer) == line_count:
            buffer += 'pass'

        print()
        print(f"Add class [blue]{cls.__module__}. {cls.__name__}[/] to [red]{pyi_path}")
        with open(pyi_path, 'a') as fh:
            fh.write(str(buffer))
        # print(buffer)
