####################################################################################################
#
# EDA-RW — Python library to read/write EDA Sexpr file format
# Copyright (C) 2026 Fabrice SALVAIRE
# SPDX-License-Identifier: AGPL-3.0-or-later
#
# This file is generated by invoke task stub.generate
#
####################################################################################################

from collections.abc import Iterable, KeysView, ValuesView
from datetime import datetime
from pathlib import Path

import edarw.eda.librepcb.common
import edarw.eda.librepcb.component
import edarw.eda.librepcb.schematic
import edarw.eda.librepcb.symbol
from edarw import geometry
from edarw import sexpr
from edarw.eda import librepcb
from edarw.eda.librepcb.common import LibreSexpr, UuidSexpr
from edarw.sexpr import SexprWrapper

####################################################################################################

type UUID = str

####################################################################################################

class Variant(UuidSexpr):
    @property
    def name(self) -> str: ...
    @property
    def description(self) -> str: ...

####################################################################################################

class Netclass(UuidSexpr):
    @property
    def name(self) -> str: ...
    @property
    def default_trace_width(self) -> str: ...
    @property
    def default_via_drill_diameter(self) -> str: ...
    @property
    def min_copper_copper_clearance(self) -> float: ...
    @property
    def min_copper_width(self) -> float: ...
    @property
    def min_via_drill_diameter(self) -> float: ...

####################################################################################################

class Net(UuidSexpr):
    """Class to implement a net"""
    @property
    def netclass_obj(self: LibreSexpr) -> dict[str, LibreSexpr] | SexprWrapper | None: ...
    @property
    def signals(self) -> list[Signal]: ...

    @property
    def auto(self) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def netclass(self) -> UUID: ...

####################################################################################################

class Attribute(LibreSexpr):
    @property
    def name(self) -> str: ...
    @property
    def type(self) -> str: ...
    @property
    def unit(self) -> str: ...
    @property
    def value(self) -> str: ...

####################################################################################################

class Signal(UuidSexpr):
    @property
    def component(self) -> Component: ...
    @property
    def net_name(self) -> str | None: ...
    @property
    def net_obj(self: LibreSexpr) -> dict[str, LibreSexpr] | SexprWrapper | None: ...
    @property
    def signal_def(self): ...
    # ~ERROR~: 'property' object has no attribute 'Signal'

    @property
    def net(self) -> UUID: ...

####################################################################################################

class Component(UuidSexpr):
    """Class to implement a net"""
    @property
    def circuit(self) -> Circuit: ...
    @property
    def component_def(self): ...
    # ~ERROR~: name 'component' is not defined
    @property
    def evaluated_value(self) -> str: ...
    @property
    def lib_component_obj(self: LibreSexpr) -> dict[str, LibreSexpr] | SexprWrapper | None: ...
    @property
    def lib_variant_obj(self: LibreSexpr) -> dict[str, LibreSexpr] | SexprWrapper | None: ...

    @property
    def lib_component(self) -> UUID: ...
    @property
    def lib_variant(self) -> UUID: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> str: ...
    @property
    def lock_assembly(self) -> bool: ...
    @property
    def attribute(self) -> list[Attribute]: ...
    @property
    def signal(self) -> list[Signal]: ...

####################################################################################################

class Circuit(LibreSexpr):
    """Class to read a LibrePCB Circuit"""
    def get_net(self, uuid: UUID) -> Net: ...
    @property
    def project(self): ...
    # ~ERROR~: name 'Project' is not defined

    @property
    def variant(self) -> Variant: ...
    @property
    def netclass(self) -> list[Netclass]: ...
    @property
    def net(self) -> list[Net]: ...
    @property
    def component(self) -> list[Component]: ...
