####################################################################################################
#
# EDA-RW — Python library to read/write EDA Sexpr file format
# Copyright (C) 2026 Fabrice SALVAIRE
# SPDX-License-Identifier: AGPL-3.0-or-later
#
# This file is generated by invoke task stub.generate
#
####################################################################################################

from collections.abc import Iterable, KeysView, ValuesView
from datetime import datetime
from pathlib import Path

import edarw.eda.librepcb.circuit
import edarw.eda.librepcb.component
import edarw.eda.librepcb.schematic
import edarw.eda.librepcb.symbol
from edarw import geometry
from edarw import sexpr
from edarw.eda import librepcb
from edarw.sexpr import SexprWrapper

####################################################################################################

type UUID = str

####################################################################################################

class LibreSexpr(SexprWrapper):
    def class_name() -> str: ...
    def dump_uuids() -> None: ...
    def get_uuid(uuid: UUID) -> dict[str, LibreSexpr]: ...
    def get_uuid_cls(uuid: UUID, class_name: str) -> LibreSexpr: ...

    @property
    def _UUID_MAP(self) -> dict: ...

####################################################################################################

class UuidSexpr(LibreSexpr):
    @property
    def uuid(self) -> UUID: ...
