####################################################################################################
#
# EDA-RW — Python library to read/write EDA Sexpr file format
# Copyright (C) 2026 Fabrice SALVAIRE
# SPDX-License-Identifier: AGPL-3.0-or-later
#
# This file is generated by invoke task stub.generate
#
####################################################################################################

from collections.abc import Iterable, KeysView, ValuesView
from datetime import datetime
from pathlib import Path

import edarw.eda.librepcb.circuit
import edarw.eda.librepcb.common
import edarw.eda.librepcb.component
import edarw.eda.librepcb.schematic
import edarw.eda.librepcb.symbol
from edarw import geometry
from edarw import sexpr
from edarw.eda import librepcb
from edarw.eda.librepcb.common import LibreSexpr, UuidSexpr
from edarw.sexpr import SexprWrapper

####################################################################################################

type UUID = str

####################################################################################################

class Project(UuidSexpr):
    """Class to read a LibrePCB Project"""
    @property
    def circuit(self) -> librepcb.circuit.Circuit: ...
    def component(self, uuid: UUID) -> librepcb.component.Component: ...
    @property
    def components(self) -> ValuesView[librepcb.component.Component]: ...
    @property
    def project_path(self) -> Path: ...
    @property
    def schematic(self) -> librepcb.schematic.Schematic: ...
    def symbol(self, uuid: UUID) -> librepcb.symbol.Symbol: ...
    @property
    def symbols(self) -> ValuesView[librepcb.symbol.Symbol]: ...

    @property
    def name(self) -> str: ...
    @property
    def author(self) -> str: ...
    @property
    def version(self) -> str: ...
    @property
    def created(self) -> datetime: ...
