####################################################################################################
#
# EDA-RW — Python library to read/write EDA Sexpr file format
# Copyright (C) 2026 Fabrice SALVAIRE
# SPDX-License-Identifier: AGPL-3.0-or-later
#
# This file is generated by invoke task stub.generate
#
####################################################################################################

from collections.abc import Iterable, KeysView, ValuesView
from datetime import datetime
from pathlib import Path

import edarw.eda.librepcb.circuit
import edarw.eda.librepcb.common
import edarw.eda.librepcb.component
import edarw.eda.librepcb.schematic
import edarw.eda.librepcb.symbol
from edarw import geometry
from edarw import sexpr
from edarw.eda import librepcb
from edarw.eda.librepcb.common import LibreSexpr, UuidSexpr
from edarw.sexpr import SexprWrapper

####################################################################################################

type UUID = str

####################################################################################################

class Text(UuidSexpr):
    @property
    def position_obj(self: LibreSexpr) -> geometry.Position: ...

    @property
    def layer(self) -> str: ...
    @property
    def height(self) -> float: ...
    @property
    def align(self) -> list[str]: ...
    @property
    def position(self) -> tuple[float, float]: ...
    @property
    def rotation(self) -> int: ...
    @property
    def lock(self) -> bool: ...
    @property
    def value(self) -> str: ...

####################################################################################################

class Symbol(UuidSexpr):
    @property
    def component_obj(self: LibreSexpr) -> librepcb.component.Component: ...
    @property
    def lib_gate_obj(self: LibreSexpr) -> librepcb.component.Gate: ...
    @property
    def position_obj(self: LibreSexpr) -> geometry.Position: ...
    @property
    def project(self) -> librepcb.project.Project: ...
    # ~ERROR~: name 'Project' is not defined
    @property
    def schematic(self) -> Schematic: ...

    @property
    def component(self) -> UUID: ...
    @property
    def lib_gate(self) -> UUID: ...
    @property
    def position(self) -> tuple[float, float]: ...
    @property
    def rotation(self) -> int: ...
    @property
    def mirror(self) -> bool: ...
    @property
    def text(self) -> list[Text]: ...

####################################################################################################

class Grid(LibreSexpr):
    @property
    def interval(self) -> float: ...
    @property
    def unit(self) -> str: ...

####################################################################################################

class FromMixin(LibreSexpr):
    @property
    def is_junction(self) -> bool: ...
    @property
    def is_pin(self) -> bool: ...
    @property
    def junction_obj(self: LibreSexpr) -> Junction: ...
    @property
    def pin_obj(self: LibreSexpr) -> dict[str, LibreSexpr] | SexprWrapper | None: ...
    @property
    def position(self) -> geometry.Position: ...
    @property
    def symbol_obj(self: LibreSexpr) -> librepcb.symbol.Symbol: ...

    @property
    def symbol(self) -> UUID: ...
    @property
    def pin(self) -> UUID: ...
    @property
    def junction(self) -> UUID: ...

####################################################################################################

class From(FromMixin): ...

####################################################################################################

class To(FromMixin): ...

####################################################################################################

class Line(UuidSexpr):
    @property
    def width(self) -> float: ...
    @property
    def from_(self) -> From: ...
    @property
    def to(self) -> To: ...

####################################################################################################

class Junction(UuidSexpr):
    @property
    def position_obj(self: LibreSexpr) -> geometry.Position: ...

    @property
    def position(self) -> tuple[float, float]: ...

####################################################################################################

class NetSegment(UuidSexpr):
    def get_jonction(self, uuid: UUID) -> Junction: ...
    @property
    def net_obj(self: LibreSexpr) -> dict[str, LibreSexpr] | SexprWrapper | None: ...

    @property
    def net(self) -> UUID: ...
    @property
    def junction(self) -> list[Junction]: ...
    @property
    def line(self) -> list[Line]: ...

####################################################################################################

class Schematic(UuidSexpr):
    def get_netsegment(self, uuid: UUID) -> NetSegment: ...
    def get_symbol(self, uuid: UUID) -> Symbol: ...
    @property
    def project(self) -> librepcb.project.Project: ...
    # ~ERROR~: name 'Project' is not defined

    @property
    def name(self) -> str: ...
    @property
    def grid(self) -> Grid: ...
    @property
    def symbol(self) -> list[Symbol]: ...
    @property
    def netsegment(self) -> list[NetSegment]: ...
